### ISSUE TITLE
قابلیت جستجو

### ISSUE THREAD

**Issue by evokelektrique** [Webamoozcom/warning-list#6]
<p align="right">
در صورت زیاد شدن موارد نیاز بودن یک فرم جستجو میتونه خیلی کاربری باشه، من توانایی ساختنش رو دارم اگه مایلید تا یک فرم جستجو اضافه بکنم
</p>

**Comment by Webamoozcom** [comment]
بله حتما، عالیه👍😊
یک اسکریپت ساده و با قابلیت اجرا در بیشتر پلتفرمها خیلی عالی میشه

**Comment by Webamoozcom** [comment]
دمت گرم خیلی عالی شد
